version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    target-branch: "main"
    labels:
      - dependencies
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "nx*"
      - dependency-name: "@nx*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    target-branch: "v5"
    labels:
      - dependencies
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "nx*"
      - dependency-name: "@nx*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]