name: 'SonarCloud Scan'
description: 'Run SonarQube scan for a given path'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  SONAR_TOKEN:
    description: 'SonarCloud token'
    required: true
  path:
    description: 'Paths from matrix'
    required: true

runs:
  using: 'composite'
  steps:
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        SONAR_URL: 'https://sonarcloud.io'
      with:
        projectBaseDir: libs/${{ inputs.path }}/
        args: >
          -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}_${{ inputs.path }}
          -Dsonar.host.url=$SONAR_URL
          -Dsonar.organization=${{ github.repository_owner }}
          -Dsonar.scm.disabled=true
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.javascript.coveragePlugin=lcov
          -Dsonar.javascript.lcov.reportPaths=../../reports/${{ inputs.path }}/coverage/lcov.info
          -Dsonar.testExecutionReportPaths=../../reports/${{ inputs.path }}/sonarqube_report.xml
          -Dsonar.working.directory=../../reports/${{ inputs.path }}/.scannerwork
          -Dsonar.coverage.exclusions=**/*.ts,**/*.js,**/*.module.ts,**/*.main.ts,**/environments/**,**/assets/**,**/generated/**,**/*.stories.ts,**/*.harness
          -Dsonar.test.inclusions=/**/*.spec.ts
