name: ci-common

on:
  workflow_call:

jobs:
  codeql:
    uses: onecx/ci-angular/.github/workflows/angular-codeql.yml@v1
    secrets: inherit
  lint-test-build-sonarUpload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint affected
        run: npx nx affected -t lint
      - name: Test affected
        run: npx nx affected -t test --configuration=ci
      - name: Build affected
        run: npx nx affected -t build
      # store github action pr number to file
      - name: Create sonar json file
        if: github.event_name == 'push'
        run: echo ${{ github.event.number }} > github-action-pr.txt
      # upload github action pr number
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: github-action-pr
          path: github-action-pr.txt
        # upload target for next jobs
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            package.json      
            dist/
            reports/
          retention-days: 1
          if-no-files-found: ignore
