name: ci-common

on:
  workflow_call:

jobs:
  lint-test-build-sonarUpload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: nrwl/nx-set-shas@v3

      - name: Install deps
        run: npm ci

      - name: Lint affected
        run: |
          npx nx lint accelerator

      - name: Build affected
        run: |
          npx nx build accelerator

      - name: Test affected
        run: |
          npx nx test accelerator --configuration=ci

      - name: Upload Sonar artefacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            package.json      
            libs/accelorator/reports/
          retention-days: 1
          if-no-files-found: ignore
