name: Monorepo SonarQube Analysis

on:
  workflow_call:

jobs:
  find-paths:
    runs-on: ubuntu-latest
    outputs:
      paths-to-libs: ${{ steps.find-paths.outputs.paths }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find project paths
        id: find-paths
        run: |
          paths=$(find libs -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)
          echo "paths=$(echo $paths | jq -R -s -c 'split(\"\\n\")[:-1]')" >> "$GITHUB_OUTPUT"
