name: Monorepo SonarQube Analysis

on:
  workflow_call:

jobs:
  find-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find project paths
        id: find-paths
        run: |
          paths=$(find libs -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)
          for path in $paths; do
            echo "reports/$path/coverage/lcov.info"
          done > reports_paths.txt

      - run: cat reports_paths.txt

      - name: Upload paths file
        uses: actions/upload-artifact@v4
        with:
          name: paths-file
          path: paths.json
          retention-days: 1
          if-no-files-found: ignore
