name: ci-lint

on:
  workflow_call:

jobs:
  ci-lint-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: nrwl/nx-set-shas@v3

      - name: Install deps
        run: npm ci

      - name: Run Lint
        run: |
          npx nx run-many -t lint
