name: My Test Monorepo Project

on:
  workflow_call:
    inputs:
      node:
        description: 'Node version'
        default: '20'
        required: false
        type: string
      artifact:
        description: 'Name of the artifact for the build'
        default: 'package'
        required: false
        type: string
      artifactPath:
        description: 'Artifact path'
        default: '.'
        required: false
        type: string

jobs:
  download-artefact:
    name: setup-sonar-and-node
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls -lsah
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: pwd && ls -lsah
      # setup node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
          cache: 'npm'
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifactPath }}
      - run: pwd && ls -lsah
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: 'https://sonarcloud.io'
        with:
          projectBaseDir: reports/accelerator/
          args: >
            -Dsonar.projectKey=mholzaepfel_onecx-portal-ui-libs
            -Dsonar.host.url=$SONAR_URL
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.testExecutionReportPaths=./reports/accelerator/sonarqube_report.xml
            -Dsonar.javascript.lcov.reportPaths=./reports/accelerator/coverage/lcov.info          
            -Dsonar.test.inclusions=src/lib/**/*.spec.ts
