name: CI on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop
      - v3

jobs:
  dependency-review:
    uses: onecx/ci-common/.github/workflows/dependency-review.yml@v1
    secrets: inherit
    with:
      failOnSeverity: 'high'

  codeql:
    uses: onecx/ci-angular/.github/workflows/angular-codeql.yml@v1
    secrets: inherit
  ci-lint:
    uses: ./.github/workflows/ci-lint.yml
    secrets: inherit

  ci-build:
    uses: ./.github/workflows/ci-build.yml
    secrets: inherit

  ci-find-paths:
    uses: ./.github/workflows/ci-find-paths.yml
    secrets: inherit

  ci-test:
    needs: ci-find-paths
    uses: ./.github/workflows/ci-test.yml
    secrets: inherit

  ci-sonar:
    needs: ci-test
    uses: ./.github/workflows/ci-sonar.yml
    secrets: inherit
