name: On PR

on:
  pull_request:

jobs:
  dependency-review:
    uses: onecx/ci-common/.github/workflows/dependency-review.yml@v1
    secrets: inherit
    with:
      failOnSeverity: 'high'

  ci-common:
    uses: ./.github/workflows/ci-common.yml
    secrets: inherit
