name: CI Pull Request

on:
  pull_request:
    branches:
      - main
      - develop
      - v3

jobs:
  ci-common:
    uses: ./.github/workflows/ci-common.yml
    secrets: inherit
  ci-sonar:
    uses: ./.github/workflows/ci-sonar.yml
    secrets: inherit
