name: On Push

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
jobs:
  ci-common:
    uses: ./.github/workflows/ci-common.yml
    secrets: inherit

  sonar:
    needs: ci-common
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
