name: ci-test

on:
  workflow_call:

jobs:
  ci-test-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: nrwl/nx-set-shas@v3

      - name: Install deps
        run: npm ci

      - name: Test affected
        run: |
          npx nx run-many -t test -p accelerator angular-utils portal-integration-angular angular-auth --watch=false --browsers=ChromeHeadless --coverage

      - name: Change relativ path to absolute path with sed
        run: |
          cat libs/angular-utils/reports/coverage/lcov.info
          echo "bevor"
          PROJECT_ROOT=$(pwd)
          sed -i "s+libs/angular-utils/src+${PROJECT_ROOT}/libs/angular-utils/src+g" libs/angular-utils/reports/coverage/lcov.info
          cat libs/angular-utils/reports/coverage/lcov.info
          echo "Pfade in lcov.info wurden erfolgreich aktualisiert."

      - name: find paths
        run: |
          paths=$(find libs -type d -maxdepth 1 -mindepth 1 -exec basename {} \;)
          echo "name=paths::$(echo $paths | jq -R -s -c 'split("\n")[:-1]')" > paths.txt
          echo "Found paths: $paths"

      - run: |
          pwd && ls -lsah
          cat paths.txt

      - name: Upload Sonar artefacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            package.json      
            libs/accelerator/reports/
            libs/angular-utils/reports/
            libs/portal-integration-angular/reports/
            reports/
          retention-days: 1
          if-no-files-found: ignore
