name: ci-test

on:
  workflow_call:

jobs:
  ci-test-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: nrwl/nx-set-shas@v3

      - name: Install deps
        run: npm ci

      - name: Test affected
        run: |
          npx nx run-many -t test -p angular-utils --watch=false --browsers=ChromeHeadless --coverage

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print paths
        run: |
          echo "Paths to libs: ${{ needs.find-paths.outputs.paths-to-libs }}"

      - name: Modify lcov.info files
        run: |
          paths="${{ needs.find-paths.outputs.paths-to-libs }}"
          for path in $(echo $paths | jq -r '.[]'); do
            lcov_file="reports/${path}/coverage/lcov.info"
            if [ -f "$lcov_file" ]; then
              sed -i "s|^SF:|SF:/|g" "$lcov_file"
              echo "Modified $lcov_file"
            else
              echo "File $lcov_file does not exist"
            fi
          done

      - name: Upload Sonar artefacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            package.json      
            reports/
          retention-days: 1
          if-no-files-found: ignore
