name: CI Push

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  codeql:
    uses: onecx/ci-angular/.github/workflows/angular-codeql.yml@v1
    secrets: inherit

  ci-common:
    uses: ./.github/workflows/ci-common.yml
    secrets: inherit

  ci-mono-sonar1:
    needs: ci-common
    uses: ./.github/workflows/ci-mono-sonar1.yml
    secrets: inherit

  ci-mono-sonar2:
    needs: ci-common
    uses: ./.github/workflows/ci-mono-sonar2.yml
    secrets: inherit

  ci-mono-sonar3:
    needs: ci-common
    uses: ./.github/workflows/ci-mono-sonar3.yml
    secrets: inherit
