name: combind build, lint, test

on:
  workflow_call:
    inputs:
      node:
        description: 'Node version'
        default: '20'
        required: false
        type: string

jobs:
  build-affected-libs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tasks: [build, lint]

    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup-environment.yml

      - name: Run affected Build
        run: |
          npx nx run-many -t ${{ matrix.tasks }}
