name: Integration Tests

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Cache and Pull Docker Images
        uses: ./.github/actions/docker-cache

      - name: Run Integration Tests
        run: |
          echo "Running integration tests with cached Docker images..."
          npx nx test integration-tests --watch=false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: |
            libs/integration-tests/coverage/
            reports/
          retention-days: 1
          if-no-files-found: ignore
