name: SonarQube Pull Request

on:
  workflow_run:
    workflows: ["On PR"]
    types:
      - completed

jobs:
  set-matrix-pr:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix-generator.outputs.matrix }}

    steps:
      - name: Generate coverage reports matrix
        id: matrix-generator
        uses: ./.github/actions/coverage-matrix-generator
        with:
          workflow_run_id: ${{ github.event.workflow_run.id }}

  sonar-scan-pr:
    needs: set-matrix-pr
    runs-on: ubuntu-latest

    # Only run this job if:
    # - The triggering workflow was for a pull request
    # - The triggering workflow completed successfully
    # - There are libraries to analyze (non-empty matrix)
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      needs.set-matrix-pr.outputs.matrix != '[]' &&
      needs.set-matrix-pr.outputs.matrix != ''

    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.set-matrix-pr.outputs.matrix) }}

    steps:
      - name: Run SonarQube PR Analysis
        uses: ./.github/actions/sonar-pr-analysis
        with:
          workflow_run_id: ${{ github.event.workflow_run.id }}
          repository_full_name: ${{ github.event.repository.full_name }}
          head_repository_full_name: ${{ github.event.workflow_run.head_repository.full_name }}
          head_branch: ${{ github.event.workflow_run.head_branch }}
          head_sha: ${{ github.event.workflow_run.head_sha }}
          event_type: ${{ github.event.workflow_run.event }}
          conclusion: ${{ github.event.workflow_run.conclusion }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          library_path: ${{ matrix.path }}
